# Cloud Build Configuration for Web Application

steps:
  # Install JFrog CLI
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fL "https://getcli.jfrog.io" | sh
        mv jfrog /workspace/jfrog
        chmod +x /workspace/jfrog

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_JFROG_URL}/${_DOCKER_REPO}/${_PROJECT_NAME}:$BUILD_ID'
      - '-t'
      - '${_JFROG_URL}/${_DOCKER_REPO}/${_PROJECT_NAME}:${_ENVIRONMENT}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_ENVIRONMENT}'
      - '.'

  # Configure JFrog CLI
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'config'
      - 'add'
      - 'rt-server'
      - '--url=https://${_JFROG_URL}'
      - '--access-token=$_JFROG_ACCESS_TOKEN'
      - '--interactive=false'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

  # Push to JFrog Artifactory
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'docker'
      - 'push'
      - '${_JFROG_URL}/${_DOCKER_REPO}/${_PROJECT_NAME}:$BUILD_ID'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'docker'
      - 'push'
      - '${_JFROG_URL}/${_DOCKER_REPO}/${_PROJECT_NAME}:${_ENVIRONMENT}'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

  # Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_ENVIRONMENT}'

  # Collect build information
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'rt'
      - 'build-collect-env'
      - '${_PROJECT_NAME}-build'
      - '$BUILD_ID'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'rt'
      - 'build-add-git'
      - '${_PROJECT_NAME}-build'
      - '$BUILD_ID'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/workspace/jfrog'
    args:
      - 'rt'
      - 'build-publish'
      - '${_PROJECT_NAME}-build'
      - '$BUILD_ID'
    secretEnv: ['_JFROG_ACCESS_TOKEN']

# Available secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/web-application-jfrog-token/versions/latest
      env: '_JFROG_ACCESS_TOKEN'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'

# Substitution variables
substitutions:
  _PROJECT_NAME: 'web-application'
  _ENVIRONMENT: 'production'
  _JFROG_URL: 'trial4jlj6w.jfrog.io'
  _DOCKER_REPO: 'shirish-docker'

# Images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_ENVIRONMENT}'
